name: Import Project Universe Standard Labels

on:
  push:
    branches: [ main, dev ]

jobs:
  labels:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: Project-Universe/standard-labels-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner-name: Project-Universe
        repository-name: supreme-tribble
